### ISSUE TITLE
Obj file loader

### ISSUE THREAD

**Issue by edsilv** [edsilv/virtex#18]
Three.js loads .obj and .mtl files separately.

http://stackoverflow.com/questions/43122400/is-there-a-way-to-load-a-mtl-using-the-path-in-the-obj-file

Is there a way to just use the .obj file to get the .mtl path and have a single file to reference (as required) in a IIIF manifest?

Aframe also specifies separate files: https://aframe.io/docs/master/components/obj-model.html

Related issue exporting diffuse texture from Blender: http://blender.stackexchange.com/questions/76697/cant-get-diffuse-texture-to-be-included-in-mtl-file

**Comment by edsilv** [comment]
First stackoverflow q answered. However, there is now the problem of loading normal maps:

http://stackoverflow.com/questions/29800214/normal-map-in-obj-file

**Comment by ponchio** [comment]
There is an [extension to mtl ](https://en.wikipedia.org/wiki/Wavefront_.obj_file#Physically-based_Rendering) to support normal maps using the key 'norm'. 

```
newmtl material_0
Ka 0.200000 0.200000 0.200000
Kd 1.000000 1.000000 1.000000
Ks 1.000000 1.000000 1.000000
Tr 0.000000
illum 2
Ns 0.000000
map_Kd hc9_diffuse.png
norm hc9_normal.png

```

I made a quick test on the normal issues and found out that by adding 3 lines to MTLLoader.js
normal maps could be supported.

```
				case 'map_ks':

					// Specular map

					setMapForType( "specularMap", value );

					break;

+				case 'norm':
+
+					setMapForType( "normalMap", value );
+
+					break;

				case 'map_bump':
				case 'bump':

					// Bump texture map

					setMapForType( "bumpMap", value );

					break;
```

Note: for the normal map to properly work, the per-vertex normals must be present in the mesh.

**Comment by edsilv** [comment]
Cool, maybe it's worth creating a PR to MTLLoader to support this? Presumably Blender won't allow you to export that `norm` key, so it would have to be added by hand?

**Comment by edsilv** [comment]
Have created a PR: https://github.com/mrdoob/three.js/pull/11827
