### ISSUE TITLE
Implement Corto Loader

### ISSUE THREAD

**Issue by edsilv** [edsilv/virtex#19]
Mesh compression: http://vcg.isti.cnr.it/corto

Mesh multiresolution: http://vcg.isti.cnr.it/nexus

Making interfaces:  http://3dhop.net/

A server which takes care of the model conversion to multiresolution format for 3d and RTI, hosting and some configuration:

http://ariadne1.isti.cnr.it

**Comment by ponchio** [comment]
I got the following error after cloning and  npm install, any suggestion?

npm ERR! git clone git@github.com:edsilv/key-codes Cloning into bare repository '/home/ponchio/.npm/_git-remotes/git-github-com-edsilv-key-codes-dfea859e'...
npm ERR! git clone git@github.com:edsilv/key-codes Warning: Permanently added 'github.com,192.30.253.113' (RSA) to the list of known hosts.
npm ERR! git clone git@github.com:edsilv/key-codes Permission denied (publickey).
npm ERR! git clone git@github.com:edsilv/key-codes fatal: Could not read from remote repository.
npm ERR! git clone git@github.com:edsilv/key-codes 
npm ERR! git clone git@github.com:edsilv/key-codes Please make sure you have the correct access rights
npm ERR! git clone git@github.com:edsilv/key-codes and the repository exists.
npm ERR! notarget No compatible version found: key-codes@'edsilv/key-codes'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.0.1"]
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! System Linux 4.2.0-42-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/ponchio/devel/virtex
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! code ETARGET

**Comment by edsilv** [comment]
I'm getting a similar error on the airport WiFi. I think it could be a problem with proxy servers: https://github.com/npm/npm/issues/2728
I'll try again when I get back to the UK. I've run into similar issues at the Wellcome Library and British Library where npm is blocked.

**Comment by edsilv** [comment]
Yep, `npm install` is working on my home WiFi. Would you mind trying again on a different WiFi network?

**Comment by ponchio** [comment]
I manage to make some progress but I got stumped at the following error:

typings ERR! message Unable to read typings for "base-component". You should check the entry paths in "base-component.bundle.d.ts" are up to date
typings ERR! caused by https://raw.githubusercontent.com/viewdir/base-component/master/dist/base-component.bundle.d.ts/index.d.ts responded with 404, expected it to equal 200
typings ERR! 

(Found no entry paths in base-component-bundle.d.ts...) Hints?

**Comment by edsilv** [comment]
I've merged the more up-to-date dev branch with master and just tested a clean npm install on windows and mac. Didn't get any errors. Could you try recloning and npm installing? Sorry..!
